### ISSUE TITLE
Missed DataSet

### ISSUE THREAD

**Issue by sdsdjr** [scilearn/FSHDMR#1]
Hello,
This Dataset does not include in Data Folder "SUNDIKEN.mat"
so when the program runs fall into exceptions
Would you pls upload this dataset
Thanks

**Comment by hkayabilisim** [comment]
Hi,

SUNDIKEN dataset was not included to the repository due to permission issues although the results related with SUNDIKEN was included.  The situation is still the same so I can not upload it to GitHub.

If you would like to get rid of the error than you can remove "SUNDIKEN" option from findFeatures.py and classification.py. (I already made the changes to them, so you can just update the repository and run the scripts again) Then the scripts will skip SUNDIKEN dataset.

Thanks

**Comment by sdsdjr** [comment]
Hi,
Thank you so much for your reply
